"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useSession } from "@/lib/use-session";
import { Transcript } from "@/components/Transcript";
import { ProgramView } from "@/components/ProgramView";
import { EvalPanel } from "@/components/EvalPanel";
import { Orb } from "@/components/Orb";

const PHASE_HELP: Record<string, string> = {
  IDLE: "Hold the button (or hold Space) and speak a coaching command.",
  LISTENING: "Listening… keep holding, then release.",
  THINKING: "Reading your instruction.",
  TOOL_RUNNING: "Updating the program.",
  SPEAKING: "Speaking. Hold to interrupt and correct me.",
  INTERRUPTING: "Stopping what I was saying.",
  RECOVERING: "Recovering.",
  COMPLETED: "Done. Say something new.",
  ERROR: "Something went wrong. Press reset.",
  CANCELLING: "Discarding the stale instruction.",
};

export default function Session() {
  const [mounted, setMounted] = useState(false);
  const { vm, actions, evalData, runtime, sttStatus, holding } = useSession();
  const [evalOpen, setEvalOpen] = useState(false);
  const [showManual, setShowManual] = useState(false);
  const [mobileTab, setMobileTab] = useState<"copilot" | "program" | "eval">("copilot");
  const holdRef = useRef(false);
  const spaceDown = useRef(false);
  const rimeConfig = runtime.rimeConfig;

  useEffect(() => {
    setMounted(true);
  }, []);

  const statusLine = PHASE_HELP[vm.phase] ?? "";

  const micBlockMessage =
    sttStatus.reason === "insecure-context"
      ? "Microphone blocked: this page must be opened via localhost or https — you are using a network address like 172.x."
      : sttStatus.reason === "unsupported-browser" || sttStatus.reason === "no-media"
        ? "Speech recognition unavailable in this browser — use Chrome or Edge on https/localhost."
        : vm.micError;

  const stopHold = useCallback(
    (cancelled: boolean) => {
      if (!holdRef.current && !spaceDown.current) return;
      holdRef.current = false;
      spaceDown.current = false;
      void actions.endHold(cancelled);
    },
    [actions],
  );

  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.code !== "Space") {
        if (e.code === "Escape") stopHold(true);
        return;
      }
      const target = e.target as HTMLElement | null;
      if (target && target.closest("input, textarea, select")) return;
      e.preventDefault();
      const active = document.activeElement;
      if (active instanceof HTMLElement) active.blur();
      if (!spaceDown.current) {
        spaceDown.current = true;
        actions.beginHold();
      }
    };
    const onKeyUp = (e: KeyboardEvent) => {
      if (e.code === "Space") stopHold(false);
    };
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("keyup", onKeyUp);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("keyup", onKeyUp);
    };
  }, [actions, stopHold]);

  if (!mounted) {
    return null;
  }

  return (
    <main className="frame" suppressHydrationWarning>
      <header className="gutter">
        <div className="gutter-l">
          <span className="wordmark" aria-hidden="true">
            Spotter
          </span>
          <span className="gutter-gap" aria-hidden="true">
            /
          </span>
          <span className="label subtitle">voice-native coaching copilot</span>
        </div>
        <div className="gutter-r">
          <span className="meta transport-badge" title={rimeConfig.endpoint}>
            {rimeConfig.transport}
          </span>
          <span className={`meta provider-badge ${vm.provider.provider === "fallback" ? "danger" : ""}`}>
            {vm.provider.provider === "fallback" ? "FALLBACK AUDIO" : `Rime · ${vm.provider.voice}`}
          </span>
          <button type="button" className="ghost-btn" onClick={() => setShowManual((v) => !v)} aria-expanded={showManual}>
            About
          </button>
        </div>
      </header>

      {showManual && (
        <section className="manual" aria-label="How to use Spotter">
          <p>
            <strong>Spotter</strong> is for strength coaches whose hands are on the bar. Speak your coaching
            commands. Interrupt Spotter mid-sentence — it stops, discards the stale instruction, and recomputes
            from your latest correction. All speech output is generated by <em>Rime</em>; the interrupt engine is
            measured in the panel below.
          </p>
          <ul>
            <li>Hold the button (or hold <kbd className="kbd">Space</kbd>), speak, then release.</li>
            <li>While Spotter is speaking, hold it again and correct it — immediately.</li>
          </ul>
        </section>
      )}

      {/* Mobile-only tab bar for switching between Copilot, Program, and Evidence */}
      <nav className="mobile-tabs" role="tablist" aria-label="Mobile navigation">
        <button
          type="button"
          role="tab"
          aria-selected={mobileTab === "copilot"}
          className={`mobile-tab ${mobileTab === "copilot" ? "active" : ""}`}
          onClick={() => setMobileTab("copilot")}
        >
          <span className="dot" aria-hidden="true" />
          Copilot
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mobileTab === "program"}
          className={`mobile-tab ${mobileTab === "program" ? "active" : ""}`}
          onClick={() => setMobileTab("program")}
        >
          Program
        </button>
        <button
          type="button"
          role="tab"
          aria-selected={mobileTab === "eval"}
          className={`mobile-tab ${mobileTab === "eval" ? "active" : ""}`}
          onClick={() => setMobileTab("eval")}
        >
          Evidence
        </button>
      </nav>

      <div className="board">
        <section
          aria-label="Voice session"
          className={`board-col col-session ${mobileTab === "copilot" ? "mobile-active" : "mobile-hidden"}`}
        >
          <div className="signal-zone">
            <Orb phase={vm.phase} level={vm.level} status={statusLine} onInterrupt={() => stopHold(true)} />
          </div>

          <div className="panel">
            <div className="panel-head">
              <span className="label">turn log</span>
              <span className="meta" aria-live="polite">
                {runtime.debug.state}
              </span>
            </div>
            <Transcript lines={vm.transcript} interim={vm.interim} />
          </div>
        </section>

        <aside
          aria-label="Live program and evidence"
          className={`board-col col-aside ${mobileTab !== "copilot" ? "mobile-active" : "mobile-hidden"}`}
        >
          <div className={`program-wrapper ${mobileTab === "program" || mobileTab === "copilot" ? "" : "mobile-hide-program"}`}>
            <ProgramView program={vm.program} />
          </div>
          <div className={`eval-wrapper ${mobileTab === "eval" ? "mobile-show-eval" : ""}`}>
            <details
              className="eval-toggle"
              open={evalOpen || mobileTab === "eval"}
              onToggle={(e) => setEvalOpen((e.target as HTMLDetailsElement).open)}
            >
              <summary className="eval-summary">
                <span className="label">evidence panel</span>
                <span className="meta">{evalOpen || mobileTab === "eval" ? "hide" : "show"}</span>
              </summary>
              <EvalPanel eval={evalData} vm={vm} />
            </details>
          </div>
        </aside>
      </div>

      {/* Global dock with talk button and demo controls - sticky on mobile */}
      <footer className="dock-container" aria-label="Interaction controls">
        <div className="dock">
          <button
            type="button"
            className="talk-button"
            data-pressed={holding ? "true" : "false"}
            onPointerDown={(e) => {
              try {
                e.currentTarget.setPointerCapture(e.pointerId);
              } catch {}
              holdRef.current = true;
              actions.beginHold();
            }}
            onPointerUp={(e) => {
              try {
                if (e.currentTarget.hasPointerCapture(e.pointerId)) {
                  e.currentTarget.releasePointerCapture(e.pointerId);
                }
              } catch {}
              stopHold(false);
            }}
            onPointerCancel={(e) => {
              try {
                if (e.currentTarget.hasPointerCapture(e.pointerId)) {
                  e.currentTarget.releasePointerCapture(e.pointerId);
                }
              } catch {}
              stopHold(true);
            }}
            onContextMenu={(e) => e.preventDefault()}
            disabled={!sttStatus.ok}
          >
            {sttStatus.ok ? (
              <>
                <span className="dot" aria-hidden="true" />
                <span>hold to talk</span>
                <span className="kbd desktop-kbd" aria-hidden="true">
                  space
                </span>
              </>
            ) : (
              "Microphone unavailable"
            )}
          </button>
          {micBlockMessage && (
            <p className="mic-block" role="alert">
              {micBlockMessage}
            </p>
          )}
          <div className="dock-secondary">
            <button type="button" className="ghost-btn" onClick={() => actions.reset()}>
              Reset session
            </button>
            <div className="dock-row" role="group" aria-label="Demo controls">
              <label className="dock-row-item">
                <span className="label">delay</span>
                <select
                  className="ghost-select"
                  defaultValue="0"
                  onChange={(e) => {
                    actions.setSimulatedDelay(Number(e.target.value));
                    e.currentTarget.blur();
                  }}
                >
                  <option value="0">0ms</option>
                  <option value="600">600ms</option>
                  <option value="1500">1500ms</option>
                </select>
              </label>
              <label className="dock-row-item">
                <span className="label">tts</span>
                <select
                  className="ghost-select"
                  defaultValue="rime"
                  onChange={(e) => {
                    actions.setFallback(e.target.value === "fallback");
                    e.currentTarget.blur();
                  }}
                >
                  <option value="rime">Rime</option>
                  <option value="fallback">browser</option>
                </select>
              </label>
            </div>
          </div>
        </div>
      </footer>
    </main>
  );
}